name: update-expirations

on:
  schedule:
    - cron: '5 0 * * *'     # Tous les jours à 00:05 UTC
  workflow_dispatch:

# Evite que 2 runs se chevauchent
concurrency:
  group: pages-update
  cancel-in-progress: true

# Permissions minimales
permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Compute expirations
        env:          
          EXPIRATIONS: ${{ vars.EXPIRATIONS }}
          CLAMP_NON_NEGATIVE: 'false'
          TIMEZONE: 'Europe/Paris'
        run: |
          echo "EXPIRATIONS=$EXPIRATIONS"
          python scripts/gen_expirations.py
          echo "=== JSON généré ==="
          cat docs/expirations.json

      # Publie exactement le dossier ./docs (pas de commit/push)
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/configure-pages@v5
      - id: deployment
        uses: actions/deploy-pages@v4
